#!/usr/bin/env node
var exec = require('child_process').exec;

// cmd/terminal commands
var commands = [];

commands.forEach(function(command) {
    exec(command, function(error, stdout, stderr) {
        if(error) {
            console.log(`[pre-push] - ${command} failed!`);
            process.exit(1);
        }
    });
});
