#!/usr/bin/env node
var exec = require('child_process').exec;

var commands = ['grunt jshint','grunt sassLint'];

for(var command in commands) {
    exec(command, function(error, stdout, stderr) {
        if(error) {
            console.log(`${command} failed`);
            process.exit(1);
        }
    });
}
